name: CI/CD Pipeline

# Required GitHub Secrets:
# - VERCEL_TOKEN: Your Vercel API token (get from https://vercel.com/account/tokens)
# - VERCEL_SCOPE: Your Vercel team/organization scope
#
# To configure secrets:
# 1. Go to your GitHub repository
# 2. Navigate to Settings > Secrets and variables > Actions
# 3. Add the required secrets

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: funnder_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Type check
      run: pnpm type-check
    
    - name: Lint
      run: pnpm lint
    
    - name: Setup test database
      run: |
        echo "DATABASE_URL=postgresql://postgres:postgres@localhost:5432/funnder_test" >> .env
        pnpm db:push
        pnpm db:generate
    
    - name: Run tests
      run: pnpm test
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/funnder_test
        NODE_ENV: test
    
    - name: Build
      run: pnpm build
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/funnder_test

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: pnpm audit --audit-level moderate
    
    - name: Check for secrets
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: main
        head: HEAD

  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    needs: [test, security]
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install Vercel CLI
      run: npm install -g vercel
    
    - name: Check Vercel configuration
      run: |
        if [ -z "$VERCEL_TOKEN" ]; then
          echo "Error: VERCEL_TOKEN secret is not configured"
          exit 1
        fi
        if [ -z "$VERCEL_SCOPE" ]; then
          echo "Error: VERCEL_SCOPE secret is not configured"
          exit 1
        fi
        echo "Vercel configuration verified"
      env:
        # Note: These secrets need to be configured in GitHub repository settings
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment"
        if [ -n "$VERCEL_TOKEN" ] && [ -n "$VERCEL_SCOPE" ]; then
          vercel --token $VERCEL_TOKEN --scope $VERCEL_SCOPE --yes
        else
          echo "Warning: VERCEL_TOKEN or VERCEL_SCOPE not configured. Skipping deployment."
          echo "Please configure these secrets in your GitHub repository settings."
        fi
      env:
        # Note: These secrets need to be configured in GitHub repository settings
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}

  deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: [test, security]
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'pnpm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 10
    
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    
    - name: Install Vercel CLI
      run: npm install -g vercel
    
    - name: Check Vercel configuration
      run: |
        if [ -z "$VERCEL_TOKEN" ]; then
          echo "Error: VERCEL_TOKEN secret is not configured"
          exit 1
        fi
        if [ -z "$VERCEL_SCOPE" ]; then
          echo "Error: VERCEL_SCOPE secret is not configured"
          exit 1
        fi
        echo "Vercel configuration verified"
      env:
        # Note: These secrets need to be configured in GitHub repository settings
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
    
    - name: Deploy to production
      run: |
        echo "Deploying to production environment"
        if [ -n "$VERCEL_TOKEN" ] && [ -n "$VERCEL_SCOPE" ]; then
          vercel --prod --token $VERCEL_TOKEN --scope $VERCEL_SCOPE --yes
        else
          echo "Warning: VERCEL_TOKEN or VERCEL_SCOPE not configured. Skipping deployment."
          echo "Please configure these secrets in your GitHub repository settings."
        fi
      env:
        # Note: These secrets need to be configured in GitHub repository settings
        VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        VERCEL_SCOPE: ${{ secrets.VERCEL_SCOPE }}
